#!/usr/bin/env python3
# config.py

from typing import List, Tuple, Dict, Any
import os

# =================================================================
# CONFIGURACIÓN Y PARÁMETROS DE ENTRADA CRÍTICOS
# =================================================================

# --- Parámetros de Entrada ---
SS2_FILE = 'P1_DHX_secondary_strucuture.ss2' 
PDB_TEMPLATE_FILE = '8vx1_DS_renum_HETATM.pdb'
ALIGN_CODE_TEMPLATE = 'template'
ALIGN_CODE_SEQUENCE = 'FullSeq' 
CHAIN_ID = "A"

# Secuencias (se recomienda cargarlas desde un archivo externo en proyectos reales)
sequence_full = "MSYDYHQNWGRDGGPRSSGGGYGGSYGGSHGGGHGGNRGSGGGGGGGGGRGGRGRHPGHLKGREIGLWYAKKQGQKNKEAERQERAVVHMDERREEQIVQLLHSVQTKNDKDEEAQISWFAPEDHGYGTEAPAENKPNSVKNVEHQEKKMINQEKRPFRIRDKYIDRDSEYLLQENEPDATLDQQLLEDLQKKKTDLRYIEMQRFREKLPSYGMQKELVNMIDNHQVTVISGETGCGKTTQVTQFILDNYIERGKGSACRIVCTQPRRISAISVAERVAAERAESCGNGNSTGYQIRLQSRLPRKQGSILYCTTGIILQWLQSDPHLSSVSHIVLDEIHERNLQSDVLMTVVKDLLSYRPDLKVVLMSATLNAEKFSEYFGNCPMIHIPGFTFPVVEYLLEDIIEKIRYVPEQKEHRSQFKKGFMQGHVNRQEKEEKEAIYKERWPGYLRELRQRYSASTVDVVEMMDDEKVDLNLIAALIRYIVLEEEDGAILVFLPGWDNISTLHDLLMSQVMFKSDKFIIIPLHSLMPTVNQTQVFKRTPPGVRKIVIATNIAETSITIDDVVYVIDGGKIKETHFDTQNNISTMSAEWVSKANAKQRKGRAGRVQPGHCYHLYNSLRASLLDDYQLPEILRTPLEELCLQIKILRLGGIAHFLSRLMDPPSNEAVLLSIKHLMELNALDKQEELTPLGVHLARLPVEPHIGKMILFGALFCCLDPVLTIAASLSFKDPFVIPLGKEKVADARRKELAKDTKSDHLTVVNAFKGWEKAKQRGFRYEKDYCWEYFLSSNTLQMLHNMKGQFAEHLLGAGFVSSRNPQDPESNINSDNEKIIKAVICAGLYPKVAKIRLNLGKKRKMVKVYTKTDGVVAIHPKSVNVEQTEFNYNWLIYHLKMRTSSIYLYDCTEVSPYCLLFFGGDISIQKDNDQETIAVDEWIIFQSPARIAHLVKELRKELDILLQEKIESPHPVDWKDTKSRDCAVLSAIIDLIKTQEKATPRNLPPRFQDGYYS/...........................--/-................------------"
pdb_aa = "LKGREIGLWYAKKQGQKNKEAERQERAVVHMDERREEQIVQLLHSVATLDQQLLEDLQKKKTDLRYIEMQRFREKLPSYGMQKELVNMIDNHQVTVISGETGCGKTTQVTQFILDNYIERGKGSACRIVCTQPRRISAISVAERVAAERAESCGNGNSTGYQIRLQSRLPRKQGSILYCTTGIILQWLQSDPHLSSVSHIVLDEIHERNLQSDVLMTVVKDLLSYRPDLKVVLMSATLNAEKFSEYFGNCPMIHIPGFTFPVVEYLLEDIIEKIRYVPEQKEHRSQFKKGFMQGHVNRQEKEEKEAIYKERWPGYLRELRQRYSASTVDVVEMMDDEKVDLNLIAALIRYIVLEEEDGAILVFLPGWDNISTLHDLLMSQVMFKSDKFIIIPLHSLMPTVNQTQVFKRTPPGVRKIVIATNIAETSITIDDVVYVIDGGKIKETHFDTQNNISTMSAEWVSKANAKQRKGRAGRVQPGHCYHLYNSLRASLLDDYQLPEILRTPLEELCLQIKILRLGGIAHFLSRLMDPPSNEAVLLSIKHLMELNALDKQEELTPLGVHLARLPVEPHIGKMILFGALFCCLDPVLTIAASLSFKDPFVIPLGKEKVADARRKELAKDTKSDHLTVVNAFKGWEKAKQRGFRYEKDYCWEYFLSSNTLQMLHNMKGQFAEHLLGAGFVSSRNPQDPESNINSDNEKIIKAVICAGLYPKVAKIRLNLGKKRKMVKVYTKTDGVVAIHPKSVNVEQTEFNYNWLIYHLKMRTSSIYLYDCTEVSPYCLLFFGGDISIQKDNDQETIAVDEWIIFQSPARIAHLVKELRKELDILLQEKIESPHPVDWKDTKSRDCAVLSAIIDLIKTQEK/...........................--/-................------------"


# --- Configuración de Procesamiento y Modelos ---
NUM_PROCESSORS = int(os.environ.get('SLURM_CPUS_PER_TASK', 1))  # Se recomeinda cambiar por el doble del .sh
NUM_MODELS_AUTO = 10000             # Número de modelos iniciales generados por AutoModel
NUM_MODELS_TO_REFINE = 20        # Número de modelos del AutoModel (Top N por DOPEHR) que entran al DOPEHRLoopModel
NUM_MODELS_LOOP = 10             # Número de modelos a generar por cada refinamiento de DOPEHRLoopModel
NUM_BEST_FINAL_MODELS = 100       # Cuántos de los mejores modelos finales se mostrarán en el ranking

# --- Configuración de Alineamiento ---
USE_MANUAL_ALIGNMENT = False    # Si es True, se usan los archivos PIR manuales
MANUAL_ALIGNMENT_FILE = 'manual_template_FullSeq.ali'        # Archivo PIR manual SIN CDE
MANUAL_ALIGNMENT_CDE_FILE = 'manual_template_FullSeq_cde.ali' # Archivo PIR manual CON CDE

# --- Variables Derivadas y Nombres de Archivo ---
ALIGNMENT_FILE = f'{ALIGN_CODE_TEMPLATE}_{ALIGN_CODE_SEQUENCE}.ali' 
ALIGNMENT_CDE_FILE = f'{ALIGN_CODE_TEMPLATE}_{ALIGN_CODE_SEQUENCE}_cde.ali' 

# Exportar las variables de configuración para el uso en otros módulos
__all__ = [
    'SS2_FILE', 'PDB_TEMPLATE_FILE', 'ALIGN_CODE_TEMPLATE', 'ALIGN_CODE_SEQUENCE', 'CHAIN_ID',
    'sequence_full', 'pdb_aa', 'NUM_PROCESSORS', 'NUM_MODELS_AUTO', 'NUM_MODELS_TO_REFINE',
    'NUM_MODELS_LOOP', 'NUM_BEST_FINAL_MODELS', 'USE_MANUAL_ALIGNMENT', 'MANUAL_ALIGNMENT_FILE',
    'MANUAL_ALIGNMENT_CDE_FILE', 'ALIGNMENT_FILE', 'ALIGNMENT_CDE_FILE'
]
